function IS_net_valid() -> bool{
  case net.type {
    NET_IP4: return is_valid_network();
    NET_IP6: return is_valid_network_v6();
    else: print "IS_NET_VALID: unexpected net.type ", net.type, " ", net; return false;
  }
}

function IS_route_from_SerinaIX_RS() -> bool {
  return bgp_large_community ~ [(4242423625, 233, *)];
}

filter Export_SerinaIX_RS {
  if !IS_NET_VALID() then reject;
  if IS_route_from_SerinaIX_RS() then reject;

  case source {
    RTS_STATIC: accept;

    RTS_BGP: {
      # self network: ibgp or self as from ebgp
      if (bgp_path.len = 0 || bgp_path.last = OWNAS) then accept;

      # optional: direct peers or downstreams
      # if bgp_path.len = 1 then accept;
    };
    
    else: reject;
  }
}

template bgp SerinaIX_RS from dnpeers {
  local as OWNAS;

  bfd;

  local role rs_client;
  enable extended messages;

  ipv4 {
    add paths rx;
    extended next hop;
    # use import filter from template
    export filter Export_SerinaIX_RS;
  };

  ipv6 {
    add paths rx;
    # use import filter from template
    export filter Export_SerinaIX_RS;
  };
}

protocol bgp DN42_SerinaIX_RS1 from SerinaIX_RS {
  neighbor fe80::89:58ff:fe96:4c77 % 'n2n-serinaix' as 4242423625;
}

# protocol bgp DN42_SerinaIX_RS2 from SerinaIX_RS {
#   neighbor fe80:: % 'n2n-serinaix' as 4242423625;
# }
